# Depending on how often these are edited, it may make more sense to put these
# into a model of their own, but as I don't have that information handy, I'm
# not going to over-complicate things at this stage for the sake of
# over-engineering.

from django_countries import countries

EXPERIENCE = (
    (1, "Not yet exporting"),
    (2, "Last 12 months"),
    (3, "More than 1 year, less than 2"),
    (4, "More than 2 years, less than 5"),
    (5, "Over 5 years, less than 10"),
    (6, "More than 10 years"),
)

GOODS_VS_SERVICES = (
    (1, "Goods"),
    (2, "Services"),
    (3, "Goods and Services"),
)

HVO_PROGRAMMES = (
  ("AER-01", "AER-01: Global Aerospace"),
  ("AFB-01", "AFB-01: Aid Funded Business Service"),
  ("AUS-05", "AUS-05: Australian Roads"),
  ("AUS-06", "AUS-06: Australia Airports"),
  ("AZE-01", "AZE-01: Azerbaijan Oil & Gas"),
  ("BHR-01", "BHR-01: Bahrain Rail"),
  ("BRA-16", "BRA-16: Shipyard & Shipbuilding Programme"),
  ("BRA-18", "BRA-18: Petrobras Business Plan 2013 - 2017"),
  ("BRA-42", "BRA-42: PPP Healthcare Programme"),
  ("BRA-43", "BRA-43: Brazilian Sports Infrastructure"),
  ("BRA-44", "BRA-44: Integrated Logistics"),
  ("BRA-45", "BRA-45: Brazilian Education"),
  ("BSC-01", "BSC-01: Big Science"),
  ("BSC-02", "BSC-02: ITER - Big Science Nuclear Fusion Project"),
  ("BWA-01", "BWA-01: Botswana Mining"),
  ("CAN-01", "CAN-01: Toronto Rail"),
  ("CHL-12", "CHL-12: Chile Mining"),
  ("CHN-14", "CHN-14: China Healthcare"),
  ("CHN-20", "CHN-20: China New Energy (Renewables)"),
  ("CHN-21", "CHN-21: China New Energy (Nuclear)"),
  ("CHN-49", "CHN-49: China Built Environment"),
  ("CHN-51", "CHN-51: China Airports"),
  ("CHN-53", "CHN-53: Chinese Commercial Aircraft Programmes"),
  ("CHN-54", "CHN-54: Clean and Energy Efficient Production"),
  ("CHN-55", "CHN-55: Technology Giants in China"),
  ("CHN-56", "CHN-56: China Education"),
  ("CHN-57", "CHN-57: China Maritime"),
  ("COL-02", "COL-02: Colombia Municipal infrastructure projects"),
  ("COL-03", "COL-03: Colombia Multiple transport projects"),
  ("COL-04", "COL-04: Colombian Education"),
  ("COL-05", "COL-05: Colombia Mining"),
  ("DNK-06", "DNK-06: Femern Link Project"),
  ("DZA-01", "DZA-01: Algeria Healthcare"),
  ("EAF-02", "EAF-02: Kenya-Ethiopia Transport Corridor"),
  ("EAK-01", "EAK-01: Kenya Gas"),
  ("EDU-01", "EDU-01: Education"),
  ("EDU-02", "EDU-02: International Curriculum Schools"),
  ("EDU-03", "EDU-03: ASEAN Education & Training"),
  ("EGY-01", "EGY-01: Suez Canal Regional Development Project"),
  ("ETH-01", "ETH-01: Transport Corridor"),
  ("EUR-02", "EUR-02: Northern Europe Offshore Wind & Interconnector projects"),
  ("FRA-01", "FRA-01: Big Science"),
  ("GIN-01", "GIN-01: Guinea Mining"),
  ("GSC-01", "GSC-01: Global Smart Cities"),
  ("HJK-01", "HJK-01: Jordan Nuclear New Build"),
  ("HKG-01", "HKG-01: Hong Kong Integrated Transport"),
  ("HKG-05", "HKG-05: Kai Tak Development"),
  ("HKG-08", "HKG-08: West Kowloon Cultural District"),
  ("HKG-09", "HKG-09: Zhuhai-Macao Bridge & Related Projects"),
  ("HKG-15", "HKG-15: Hong Kong Airport"),
  ("HKG-16", "HKG-16: Hong Kong Environment"),
  ("HKG-17", "HKG-17: Hong Kong Hospitals"),
  ("HKG-18", "HKG-18: Hong Kong Urban Regeneration & Built Heritage"),
  ("INA-01", "INA-01: Indonesia Infrastructure"),
  ("INA-04", "INA-04: Indonesia Aerospace"),
  ("IND-03", "IND-03: Indian metro opportunities"),
  ("IND-31", "IND-31: Conventional Power and Renewables"),
  ("IND-32", "IND-32: Civil Nuclear"),
  ("IND-50", "IND-50: Indian Industrial Corridors"),
  ("IND-51", "IND-51: India Healthcare"),
  ("IRQ-10", "IRQ-10: Iraq Oil & Gas"),
  ("IRQ-11", "IRQ-11: Iraq Federal Water Projects"),
  ("JPN-07", "JPN-07: Fukushima Decommissioning"),
  ("JPN-08", "JPN-08: Japan - Major Sporting Events"),
  ("KAZ-07", "KAZ-07: Kazakhstan Mining"),
  ("KAZ-02", "KAZ-02: Multiple Oil & Gas Projects"),
  ("KAZ-03", "KAZ-03: Kazakhstan Infrastructure"),
  ("KAZ-06", "KAZ-06: Kazakhstan Education and Training"),
  ("KAZ-07", "KAZ-07: Kazakhstan Mining"),
  ("KOR-05", "KOR-05: Global Sports Projects in Korea"),
  ("KWT-01", "KWT-01: Kuwait Airport Redevelopment"),
  ("KWT-02", "KWT-02: Boubyan Island Development"),
  ("KWT-03", "KWT-03: New Hospitals Project"),
  ("KWT-04", "KWT-04: Kuwait Metro System"),
  ("LBY-01", "LBY-01: Libya Infrastructure"),
  ("LBY-02", "LBY-02: Libya Healthcare"),
  ("LBY-03", "LBY-03: Libya Water"),
  ("LBY-04", "LBY-04: Libya Airports"),
  ("MAC-01", "MAC-01: Macau Retail & Leisure"),
  ("MEX-04", "MEX-04: Mexico Oil and Gas"),
  ("MEX-05", "MEX-05: Mexican Education"),
  ("MEX-07", "MEX-07: Veracruz Port Expansion"),
  ("MEX-08", "MEX-08: Mexico Airports"),
  ("MIN-01", "MIN-01: Global Mining Supply Chains"),
  ("MIN-02", "MIN-02: Energy for the West African Mining Industry (West African Power Pool/WAPP)"),
  ("MOR-01", "MOR-01: Morocco Mining"),
  ("MOZ-01", "MOZ-01: Mozambique Gas"),
  ("MYS-06", "MYS-06: Malaysian Transport Projects"),
  ("MYS-07", "MYS-07: Malaysia Education"),
  ("NGA-05", "NGA-05: Nigeria Oil & Gas projects"),
  ("NOR-01", "NOR-01: Oil & Gas Norway"),
  ("NUC-01", "NUC-01: Central European Nuclear"),
  ("NUC-04", "NUC-04: Nuclear Vendor Strategy"),
  ("NUC-05", "NUC-05: Western Europe Decommissioning"),
  ("NZL-01", "NZL-01: Christchurch Reconstruction"),
  ("OAG-01", "OAG-01: East Africa Oil & Gas"),
  ("OMN-01", "OMN-01: Omani Railway Network"),
  ("OMN-05", "OMN-05: OMAN Healthcare"),
  ("OTH-11", "OTH-11: Aid Funded Business Service"),
  ("OTH-12", "OTH-12: Building Creative Hubs Internationally"),
  ("OTH-13", "OTH-13: Creative Industries HVO Taskforce"),
  ("OTH-14", "OTH-14: Creative Tax Credits"),
  ("OTH-14", "OTH-14: Creative Tax Credits"),
  ("OTH-15", "OTH-15: Food and Drink Export Action Plan"),
  ("OTH-16", "OTH-16: Free Trade Agreements"),
  ("OTH-18", "OTH-18: Global E Retail (Digital Export Growth) Programme"),
  ("OTH-22", "OTH-22: UK Retail Industry - International Action Plan"),
  ("PAN-01", "PAN-01: Panama Canal Megaprojects"),
  ("PAN-02", "PAN-02: Panama City Metro Lines 2 and 3"),
  ("PER-01", "PER-01: Peru Mass Rapid Transport System"),
  ("PER-03", "PER-03: Peru Mining"),
  ("PER-04", "PER-04: Lima 2019 Pan-American Games"),
  ("PHL-09", "PHL-09: PPP Infrastructure Projects"),
  ("POL-01", "POL-01: Polish Rail"),
  ("QAT-04", "QAT-04: Qatari Rail Network"),
  ("QAT-06", "QAT-06: World Cup 2022"),
  ("QAT-07", "QAT-07: Qatari National Food Security Programme"),
  ("QAT-08", "QAT-08: Qatar Education and Training"),
  ("REN-01", "REN-01: Northern Europe Offshore Wind & Interconnector Projects"),
  ("RUS-50", "RUS-50: Russian Sports Infrastructure Projects"),
  ("RUS-52", "RUS-52: Russia Oil"),
  ("RUS-54", "RUS-54: Russia Experience Economy"),
  ("SAU-06", "SAU-06: Saudi Railways Development Programme"),
  ("SAU-08", "SAU-08: Healthcare Development Programme"),
  ("SAU-15", "SAU-15: Saudi Airport Developments"),
  ("SAU-17", "SAU-17: Saudi Water Projects"),
  ("SAU-19", "SAU-19: Saudi Arabia Oil & Gas"),
  ("SAU-20", "SAU-20: Saudi Nuclear - New Build"),
  ("SAU-21", "SAU-21: Saudi Education"),
  ("SAU-22", "SAU-22: Jeddah Urban Redevelopment Programme"),
  ("SGP-06", "SGP-06: Mass Rapid Transport"),
  ("SGP-07", "SGP-07: Changi Airport"),
  ("SGP-08", "SGP-08: Singapore Water"),
  ("SPO-01", "SPO-01: Central Asia Major Sports Events"),
  ("SSA-01", "SSA-01: Angola Oil & Gas"),
  ("TGA-01", "TGA-01: Technology Giants in SE Asia"),
  ("TGU-01", "TGU-01: Technology Giants in the USA"),
  ("THA-01", "THA-01: Flood Management & Transport Infrastructure"),
  ("THA-10", "THA-10: Thailand Rail & Airport"),
  ("TUR-26", "TUR-26: Turkey Nuclear New Build"),
  ("TUR-27", "TUR-27: Istanbul Airport"),
  ("TUR-28", "TUR-28: PPP & Healthcare"),
  ("TWN-15", "TWN-15: Rail Projects"),
  ("TWN-19", "TWN-19: Taiwan Renewables"),
  ("TWN-20", "TWN-20: Taiwan Nuclear"),
  ("TZA-01", "TZA-01: Tanzania Gas"),
  ("UAE-04", "UAE-04: UAE Rail Project"),
  ("UAE-05", "UAE-05: UAE Experience Economy"),
  ("UAE-12", "UAE-12: UAE Healthcare"),
  ("UAE-13", "UAE-13: UAE Expo 2020"),
  ("UAE-19", "UAE-19: Dubai Airport Expansion"),
  ("UAE-20", "UAE-20: UAE Education"),
  ("UAE-27", "UAE-27: "),
  ("UGA-01", "UGA-01: Uganda Gas"),
  ("UKR-01", "UKR-01: Ukraine Aerospace"),
  ("USA-26", "USA-26: US Water Sector Capital Improvement Program/Plan"),
  ("USA-31", "USA-31: US Infrastructure"),
  ("USA-32", "USA-32: North American Aircraft Programmes"),
  ("VNM-30", "VNM-30: Vietnam Urban Regeneration and Transport Projects"),
  ("VNM-31", "VNM-31: Vietnam Nuclear New Build"),
)

PROGRAMMES = (
    (1, "Afterburner"),
    (2, "Aid Funded Business Service (AFBS)"),
    (3, "Britain Open for Business"),
    (4, "British Business Network"),
    (5, "British Defence Staff - US"),
    (6, "Business Win FCO Involvement"),
    (7, "Catalyst Members Activities"),
    (8, "CEN Adv Engineering"),
    (9, "CEN Adv Manufacturing"),
    (10, "CEN Defence & Security"),
    (11, "CEN Energy"),
    (12, "CEN Health & Life Science"),
    (13, "CEN Infrastructure"),
    (14, "CEN Life Science"),
    (15, "CEN Security"),
    (16, "CEN Services"),
    (17, "Commonwealth Games"),
    (18, "Digital Trade Advisor"),
    (19, "E-Exporting"),
    (20, "Emerging Markets Contract (CEE)"),
    (21, "Emerging Markets Contract (Gulf)"),
    (22, "Emerging Markets Contract (LA)"),
    (23, "Emerging Markets Contract (Russia)"),
    (24, "Events Alliance"),
    (25, "Export Communication Review Scheme (ECR)"),
    (26, "Export Growth Service"),
    (27, "Export Oriented FDI"),
    (28, "Exporting is GREAT (EiG)"),
    (29, "EY Specialist Business Win"),
    (30, "First Time Exporters Programme"),
    (31, "Free Trade Agreements"),
    (32, "GCP"),
    (33, "GCP - Deloitte"),
    (34, "GCP - EY"),
    (35, "GCP - HSBC"),
    (36, "GCP - KPMG"),
    (37, "GCP - Lloyds"),
    (38, "GCP - PwC"),
    (39, "GCP - RBS"),
    (40, "GCP - Santander"),
    (41, "GCP - Standard Chartered"),
    (42, "GREAT Branded Event Great Campaign"),
    (43, "GREAT Challenge Fund"),
    (44, "GREAT Funded Activity"),
    (45, "GREAT Weeks"),
    (46, "Grown in Britain Global Business Programme"),
    (47, "HVO Specialist [involvement]"),
    (48, "III - Deal Ticket Size"),
    (49, "Innovation Programme"),
    (50, "International Festival for Business"),
    (51, "JETCO"),
    (52, "Low Carbon Initiative"),
    (53, "Luxury Retail"),
    (54, "Milan Expo 2015"),
    (55, "MSB Programme"),
    (56, "Music Export Growth Scheme (MEGS)"),
    (57, "Northern Powerhouse (NPH)"),
    (58, "Offshore Wind Investment Organisation"),
    (59, "Olympics 2012"),
    (60, "Overseas Market Introduction Service (OMIS)"),
    (61, "PA Specialist Business Win"),
    (62, "Reshore UK"),
    (63, "Rugby World Cup - Business Festival"),
    (64, "Shakespeare Lives"),
    (65, "Stakeholder Engagement"),
    (66, "Technology Strategy Board (TSB)"),
    (67, "UK Israel Tech Hub"),
    (68, "Venture Capital"),
    (69, "Web-based Exporting Programme"),
)

RATINGS = (
    (0, "N/A"),
    (1, "1"),
    (2, "2"),
    (3, "3"),
    (4, "4"),
    (5, "5"),
)

SECTORS = (
    (1, "Advanced Engineering"),
    (2, "Aerospace"),
    (3, "Aerospace : Aircraft Design"),
    (4, "Aerospace : Component Manufacturing"),
    (5, "Aerospace : Component Manufacturing : Engines"),
    (6, "Aerospace : Component Manufacturing : test widgerts"),
    (7, "Aerospace : Maintenance"),
    (8, "Aerospace : Manufacturing and Assembly"),
    (9, "Aerospace : Manufacturing and Assembly : Aircraft"),
    (10, "Aerospace : Manufacturing and Assembly : Helicopters"),
    (11, "Aerospace : Manufacturing and Assembly : Space Technology"),
    (12, "Aerospace : Manufacturing and Assembly : UAVs"),
    (13, "Agriculture, Horticulture and Fisheries"),
    (14, "Airports"),
    (15, "Automotive"),
    (16, "Automotive : Automotive Maintenance"),
    (17, "Automotive : Automotive Retail"),
    (18, "Automotive : Component Manufacturing"),
    (19, "Automotive : Component Manufacturing : Bodies and Coachwork"),
    (20, "Automotive : Component Manufacturing : Electronic Components"),
    (21, "Automotive : Component Manufacturing : Engines and Transmission"),
    (22, "Automotive : Component Manufacturing : Tyres"),
    (23, "Automotive : Design Engineering"),
    (24, "Automotive : Manufacturing and Assembly"),
    (25, "Automotive : Manufacturing and Assembly : Agricultural Machinery"),
    (26, "Automotive : Manufacturing and Assembly : Bicycles"),
    (27, "Automotive : Manufacturing and Assembly : Caravans"),
    (28, "Automotive : Manufacturing and Assembly : Cars"),
    (29, "Automotive : Manufacturing and Assembly : Containers"),
    (30, "Automotive : Manufacturing and Assembly : Invalid Carriages"),
    (31, "Automotive : Manufacturing and Assembly : Lorries"),
    (32, "Automotive : Manufacturing and Assembly : Motorcycles"),
    (33, "Automotive : Manufacturing and Assembly : Trailers"),
    (34, "Automotive : Manufacturing and Assembly : Vans"),
    (35, "Automotive : Motorsport"),
    (36, "Biotechnology and Pharmaceuticals"),
    (37, "Biotechnology and Pharmaceuticals : Bio and Pharma Marketing and Sales"),
    (38, "Biotechnology and Pharmaceuticals : Bio and Pharma Marketing and Sales : Bio and Pharma Retail"),
    (39, "Biotechnology and Pharmaceuticals : Bio and Pharma Marketing and Sales : Bio and Pharma Wholesale"),
    (40, "Biotechnology and Pharmaceuticals : Biotechnology"),
    (41, "Biotechnology and Pharmaceuticals : Biotechnology : Agribio"),
    (42, "Biotechnology and Pharmaceuticals : Biotechnology : Biodiagnostics"),
    (43, "Biotechnology and Pharmaceuticals : Biotechnology : Biomanufacturing"),
    (44, "Biotechnology and Pharmaceuticals : Biotechnology : Bioremediation"),
    (45, "Biotechnology and Pharmaceuticals : Biotechnology : Biotherapeutics"),
    (46, "Biotechnology and Pharmaceuticals : Biotechnology : Industrialbio"),
    (47, "Biotechnology and Pharmaceuticals : Biotechnology : Platform Technologies"),
    (48, "Biotechnology and Pharmaceuticals : Clinical Trials"),
    (49, "Biotechnology and Pharmaceuticals : Lab Services"),
    (50, "Biotechnology and Pharmaceuticals : Lab Services : Contract Research"),
    (51, "Biotechnology and Pharmaceuticals : Lab Services : Reagents, Consumables and Instruments"),
    (52, "Biotechnology and Pharmaceuticals : Pharmaceuticals"),
    (53, "Biotechnology and Pharmaceuticals : Pharmaceuticals : Basic Pharmaceutical Products"),
    (54, "Biotechnology and Pharmaceuticals : Pharmaceuticals : Drug Discovery"),
    (55, "Biotechnology and Pharmaceuticals : Pharmaceuticals : Drug Manufacture"),
    (56, "Biotechnology and Pharmaceuticals : Pharmaceuticals : Neutraceuticals"),
    (57, "Biotechnology and Pharmaceuticals : Vaccines"),
    (58, "Business (and Consumer) Services"),
    (59, "Business (and Consumer) Services : Commercial Real Estate Services"),
    (60, "Business (and Consumer) Services : Contact Centres"),
    (61, "Business (and Consumer) Services : HR Services"),
    (62, "Business (and Consumer) Services : Marketing Services"),
    (63, "Business (and Consumer) Services : Marketing Services : Market Research"),
    (64, "Business (and Consumer) Services : Shared Service Centres"),
    (65, "Chemicals"),
    (66, "Chemicals : Agricultural Chemicals"),
    (67, "Chemicals : Basic Chemicals"),
    (68, "Chemicals : Cleaning Preparations"),
    (69, "Chemicals : Miscellaneous Chemicals"),
    (70, "Chemicals : Paint, Coating and Adhesive Products"),
    (71, "Chemicals : Synthetic Materials"),
    (72, "Clothing, Footwear and Fashion"),
    (73, "Clothing, Footwear and Fashion : Clothing"),
    (74, "Clothing, Footwear and Fashion : Clothing : Workwear"),
    (75, "Clothing, Footwear and Fashion : Footwear"),
    (76, "Communications"),
    (77, "Communications : Broadband"),
    (78, "Communications : Communications Wholesale"),
    (79, "Communications : Convergent"),
    (80, "Communications : Fixed Line"),
    (81, "Communications : Mobile"),
    (82, "Communications : Mobile : 3G Services"),
    (83, "Communications : Mobile : GSM"),
    (84, "Communications : Retail"),
    (85, "Communications : Wireless"),
    (86, "Communications : Wireless : Wi-Fi"),
    (87, "Communications : Wireless : Wi-Max"),
    (88, "Construction"),
    (89, "Creative and Media"),
    (90, "Creative and Media : Architecture"),
    (91, "Creative and Media : Art, Design and Creativity"),
    (92, "Creative and Media : Art, Design and Creativity : Artistic and Literary Creation"),
    (93, "Creative and Media : Art, Design and Creativity : Arts Facilities Operation"),
    (94, "Creative and Media : Art, Design and Creativity : Design"),
    (95, "Creative and Media : Art, Design and Creativity : Fashion"),
    (96, "Creative and Media : Art, Design and Creativity : Live Theatrical Presentations"),
    (97, "Creative and Media : Creative and Media Distribution"),
    (98, "Creative and Media : Creative and Media Distribution : Film and Video"),
    (99, "Creative and Media : Creative and Media Equipment"),
    (100, "Creative and Media : Creative and Media Equipment : Musical Instrument Manufacture"),
    (101, "Creative and Media : Creative and Media Equipment : Photo and Cinema Equipment"),
    (102, "Creative and Media : Creative and Media Retail"),
    (103, "Creative and Media : Creative and Media Retail : Antiques and Antiquities"),
    (104, "Creative and Media : Creative and Media Retail : Art"),
    (105, "Creative and Media : Creative and Media Retail : Books, Newspapers and Stationery"),
    (106, "Creative and Media : Creative and Media Wholesaling"),
    (107, "Creative and Media : Creative and Media Wholesaling : Multimedia Sales"),
    (108, "Creative and Media : Creative and Media Wholesaling : Musical Instruments"),
    (109, "Creative and Media : Creative and Media Wholesaling : Photographic Goods"),
    (110, "Creative and Media : Events and Attractions"),
    (111, "Creative and Media : Media"),
    (112, "Creative and Media : Media : Advertising"),
    (113, "Creative and Media : Media : Film, Photography and Animation"),
    (114, "Creative and Media : Media : Music"),
    (115, "Creative and Media : Media : Publishing"),
    (116, "Creative and Media : Media : TV and Radio"),
    (117, "Creative and Media : Media : Video Games"),
    (118, "Creative and Media : Media Reproduction"),
    (119, "Creative and Media : Media Reproduction : Printing"),
    (120, "Creative and Media : Media Reproduction : Reproduction"),
    (121, "Defence"),
    (122, "Defence and Security"),
    (123, "Education and Training"),
    (124, "Electronics and IT Hardware"),
    (125, "Electronics and IT Hardware : Electronic Instruments"),
    (126, "Electronics and IT Hardware : Electronics and IT Technologies"),
    (127, "Electronics and IT Hardware : Electronics and IT Technologies : Broadcasting"),
    (128, "Electronics and IT Hardware : Electronics and IT Technologies : Component Technologies"),
    (129, "Electronics and IT Hardware : Electronics and IT Technologies : Computing"),
    (130, "Electronics and IT Hardware : Electronics and IT Technologies : Display Technologies"),
    (131, "Electronics and IT Hardware : Electronics and IT Technologies : Network Technologies"),
    (132, "Electronics and IT Hardware : Electronics and IT Technologies : Security Technologies"),
    (133, "Energy"),
    (134, "Environment"),
    (135, "Environment : Air Pollution and Noise Control"),
    (136, "Environment : Environmental Monitoring"),
    (137, "Environment : Fuel Cells"),
    (138, "Environment : Marine Pollution Control"),
    (139, "Environment : Sanitation and Remediation"),
    (140, "Environment : Waste Management"),
    (141, "Environment : Waste Management : Hazardous Waste Management"),
    (142, "Environment : Waste Management : Non-Metal Waste and Scrap Recycling"),
    (143, "Environment : Waste Management : Sewage Collection and Treatment"),
    (144, "Environment : Waste to Energy"),
    (145, "Environment : Water Management"),
    (146, "Environment and Water"),
    (147, "Financial Services (including Professional Services)"),
    (148, "Financial Services (including Professional Services) : Asset Management"),
    (149, "Financial Services (including Professional Services) : Banking"),
    (150, "Financial Services (including Professional Services) : Banking : Commercial Banking"),
    (151, "Financial Services (including Professional Services) : Banking : Investment Banking"),
    (152, "Financial Services (including Professional Services) : Banking : Private Banking"),
    (153, "Financial Services (including Professional Services) : Banking : Retail Banking"),
    (154, "Financial Services (including Professional Services) : Capital Markets"),
    (155, "Financial Services (including Professional Services) : Capital Markets : Hedge Funds"),
    (156, "Financial Services (including Professional Services) : Capital Markets : Private Equity"),
    (157, "Financial Services (including Professional Services) : Capital Markets : Venture Capital"),
    (158, "Financial Services (including Professional Services) : Foreign Exchange"),
    (159, "Financial Services (including Professional Services) : Insurance"),
    (160, "Financial Services (including Professional Services) : Insurance : Commercial Insurance"),
    (161, "Financial Services (including Professional Services) : Insurance : Home Insurance"),
    (162, "Financial Services (including Professional Services) : Insurance : Life Insurance"),
    (163, "Financial Services (including Professional Services) : Insurance : Motor Insurance"),
    (164, "Financial Services (including Professional Services) : Insurance : Travel Insurance"),
    (165, "Financial Services (including Professional Services) : Listings"),
    (166, "Financial Services (including Professional Services) : Professional Services"),
    (167, "Financial Services (including Professional Services) : Professional Services : Accountancy Services"),
    (168, "Financial Services (including Professional Services) : Professional Services : Legal Services"),
    (169, "Financial Services (including Professional Services) : Professional Services : Management Consultancy"),
    (170, "Food and Drink"),
    (171, "Food and Drink : Bakery Products"),
    (172, "Food and Drink : Beverages and Alcoholic Drinks"),
    (173, "Food and Drink : Brewing"),
    (174, "Food and Drink : Dairy Products"),
    (175, "Food and Drink : Food and Drink Manufacturing"),
    (176, "Food and Drink : Frozen and Chilled Foods"),
    (177, "Food and Drink : Fruit and Vegetables"),
    (178, "Food and Drink : Meat Products"),
    (179, "Food and Drink : Pet Food"),
    (180, "Food and Drink : Ready Meals"),
    (181, "Food and Drink : Secondary Food Processing"),
    (182, "Food and Drink : Tobacco Products"),
    (183, "Giftware, Jewellery and Tableware"),
    (184, "Global Sports Projects"),
    (185, "Global Sports Projects : Major Events"),
    (186, "Healthcare and Medical"),
    (187, "Healthcare and Medical : Healthcare Marketing and Sales"),
    (188, "Healthcare and Medical : Healthcare Marketing and Sales : Healthcare Retail"),
    (189, "Healthcare and Medical : Healthcare Marketing and Sales : Healthcare Wholesale"),
    (190, "Healthcare and Medical : Healthcare Services"),
    (191, "Healthcare and Medical : Healthcare Services : Dentists"),
    (192, "Healthcare and Medical : Healthcare Services : Medical Practice"),
    (193, "Healthcare and Medical : Healthcare Services : Nursing Homes"),
    (194, "Healthcare and Medical : Healthcare Services : Private Sector"),
    (195, "Healthcare and Medical : Healthcare Services : Public Sector"),
    (196, "Healthcare and Medical : Healthcare Services : Vets"),
    (197, "Healthcare and Medical : Medical Consumables"),
    (198, "Healthcare and Medical : Medical Devices and Systems"),
    (199, "Healthcare and Medical : Medical Devices and Systems : Optical Precision Instruments"),
    (200, "Healthcare and Medical : Medical Equipment"),
    (201, "Healthcare and Medical : Medical Equipment : Dental Aesthetics"),
    (202, "Healthcare and Medical : Medical Equipment : Glass"),
    (203, "Healthcare and Medical : Medical Equipment : Spectacles and Unmounted Lenses"),
    (204, "Healthcare and Medical : Medical Lab Services"),
    (205, "Household Goods, Furniture and Furnishings"),
    (206, "ICT"),
    (207, "Leisure and Tourism"),
    (208, "Leisure and Tourism : Gaming"),
    (209, "Leisure and Tourism : Gaming : Casino Gambling"),
    (210, "Leisure and Tourism : Gaming : Mass-Market Gambling"),
    (211, "Leisure and Tourism : Sports and Leisure Infrastructure"),
    (212, "Life Sciences"),
    (213, "Marine"),
    (214, "Mass Transport"),
    (215, "Mechanical Electrical and Process Engineering"),
    (216, "Metallurgical Process Plant"),
    (217, "Metals, Minerals and Materials"),
    (218, "Metals, Minerals and Materials : Ceramics"),
    (219, "Metals, Minerals and Materials : Composite Materials"),
    (220, "Metals, Minerals and Materials : Elastomers and Rubbers"),
    (221, "Metals, Minerals and Materials : Metals"),
    (222, "Metals, Minerals and Materials : Minerals"),
    (223, "Metals, Minerals and Materials : Plastics"),
    (224, "Mining"),
    (225, "More Sectors"),
    (226, "Oil and Gas"),
    (227, "Ports and Logistics"),
    (228, "Power"),
    (229, "Power : Nuclear"),
    (230, "Power : Nuclear : Nuclear De-commissiong"),
    (231, "Railways"),
    (232, "Renewable Energy"),
    (233, "Renewable Energy : Biomass"),
    (234, "Renewable Energy : Geothermal"),
    (235, "Renewable Energy : Hydro"),
    (236, "Renewable Energy : Solar"),
    (237, "Renewable Energy : Tidal"),
    (238, "Renewable Energy : Wave"),
    (239, "Renewable Energy : Wind"),
    (240, "Renewable Energy : Wind : Renewable energy: Wind: Offshore"),
    (241, "Renewable Energy : Wind : Renewable energy: Wind: Onshore"),
    (242, "Retail"),
    (243, "Security"),
    (244, "Security : Cyber Security"),
    (245, "Software and Computer Services Business to Business (B2B)"),
    (246, "Software and Computer Services Business to Business (B2B) : Biometrics"),
    (247, "Software and Computer Services Business to Business (B2B) : E-Procurement"),
    (248, "Software and Computer Services Business to Business (B2B) : Financial Applications"),
    (249, "Software and Computer Services Business to Business (B2B) : Healthcare Applications"),
    (250, "Software and Computer Services Business to Business (B2B) : Industry Applications"),
    (251, "Software and Computer Services Business to Business (B2B) : Online Retailing"),
    (252, "Software and Computer Services Business to Business (B2B) : Security Related Software"),
    (253, "Software and Computer Services Business to Business (B2B) : Support Services"),
    (254, "Software and Computer Services Business to Business (B2B) : Support Services : Equipment Maintenance and Repair"),
    (255, "Software and Computer Services Business to Business (B2B) : Support Services : Internet Service Providers"),
    (256, "Textiles, Interior Textiles and Carpets"),
    (257, "Water"),
)

TEAMS = (
    ("team", "Trade (TD or ST)"),
    ("investment", "Investment (ITFG or IG)"),
    ("dso", "DSO"),
    ("other", "Other HQ Team"),
    ("region", "UK Region"),
    ("post", "Overseas Post"),  # There's nothing for this?
)

HQ_TEAM_REGION_OR_POST = tuple([

    ("team:1", "TD - Events - Financial & Professional Business Services"),
    ("team:2", "TD - Events - Education"),
    ("team:3", "TD - Events - Services"),
    ("team:4", "TD - Events - Creative Industries"),
    ("team:5", "TD - Events - Retail"),
    ("team:6", "TD - Events - Large Events Support"),
    ("team:7", "TD - Events - Rapid Response"),
    ("team:8", "TD - Events - Large Events"),
    ("team:9", "TD - Events - Venture Capital"),
    ("team:10", "TD - Events - Energy"),
    ("team:11", "TD - Events - Advanced Manufacturing"),
    ("team:12", "TD - Events - Advanced Engineering"),
    ("team:13", "TD - Events - Agrifood"),
    ("team:14", "TD - Events - Consumer Goods"),
    ("team:15", "TD - Events - Marine"),
    ("team:16", "TD - Events - Advanced Manufacturing - Support"),
    ("team:17", "TD - Events - Planning and Procurement"),
    ("team:18", "TD - Finance & Performance"),
    ("team:19", "TD - Technology, Innovation and Events - Venture Capital Unit"),
    ("team:20", "TD - Technology, Innovation and Events - Science and Innovation"),
    ("team:21", "TD - Technology, Innovation and Events - Technology Partnerships"),
    ("team:22", "TD - Technology, Innovation and Events - Open to Export"),
    ("team:23", "TD - Technology, Innovation and Events"),
    ("team:24", "TD - Events Delivery & Performance"),
    ("team:25", "TD - Events - BDV"),
    ("team:26", "TD - Events - Markets"),
    ("team:27", "TD - TAP Team"),
    ("team:28", "TD - Business Development"),
    ("team:29", "TD - Events - Sport"),
    ("team:30", "TD - Events - Infrastructure & Life Sciences"),
    ("team:31", "TD - Events - Infrastructure"),
    ("team:32", "TD - Infrastructure & Life Sciences"),
    ("team:33", "TD - Events - ICT"),
    ("team:34", "TD - Events - Transport"),
    ("team:35", "TD - Events - Healthcare"),
    ("team:36", "TD - Events - Construction"),
    ("team:37", "TD - Events - Open to Export"),
    ("team:38", "ST - Managing Director and PA"),
    ("team:39", "ST - Infrastructure and Life Science - Healthcare Pharma and Bio"),
    ("team:40", "ST - Infrastructure & Life Science - Construction/Mass Transport"),
    ("team:41", "ST - Infrastructure and Life Science - Low Carbon Env Water"),
    ("team:42", "ST - Infrastructure and Life Science - High Value Opportunities"),
    ("team:43", "ST - Infrastructure and Life Science - Support Team"),
    ("team:44", "ST - Infrastructure and Life Science - Sport"),
    ("team:45", "ST - High Value Opportunities Activities"),
    ("team:46", "ST - Service Industries - Education and Experience Economy"),
    ("team:47", "ST - Service Industries - Financial Professional and Business"),
    ("team:48", "ST - Service Industries - Retail and Lifestyle"),
    ("team:49", "ST - Service Industries - Agri-Food Drink & Aid Funded Business"),
    ("team:50", "ST - Director - Service Industries"),
    ("team:51", "ST - Service Industries - Support Team"),
    ("team:52", "ST - Service Industries - Creative Industries"),
    ("team:53", "ST - Advanced Manufacturing - Support Team"),
    ("team:54", "ST - Advanced Manufacturing - Advanced Engineering"),
    ("team:55", "ST - Advanced Manufacturing - ICT"),
    ("team:56", "ST - Advanced Manufacturing - Energy"),
    ("team:57", "ST - Middle East"),
    ("team:58", "ST - Central and Latin America"),
    ("team:59", "ST - Russia - Turkey - Central Asia"),
    ("team:60", "ST - Africa"),
    ("team:61", "ST - Dir - Emerging Markets - China - Southern Asia"),
    ("team:62", "ST - Emerging Markets - China - Southern Asia - Support"),
    ("team:63", "ST - Emerging Markets"),
    ("team:64", "ST - China"),
    ("team:65", "ST - South Asia"),
    ("team:66", "ST - South East Asia"),
    ("team:67", "ST - Dir - Developed Markets"),
    ("team:68", "ST - Developed Markets - Support Team"),
    ("team:69", "ST - North America - East Asia - Australasia - Caribbean"),
    ("team:70", "ST - Europe"),
    ("team:71", "ST - Group Resources - Support Team"),

    ("investment:1", "ITFG - E-Business Projects Team"),
    ("investment:2", "ITFG - Overseas Resources Team"),
    ("investment:3", "ITFG - ICT & Data Policy and Support"),
    ("investment:4", "ITFG - E-Business Operational Support Team"),
    ("investment:5", "ITFG - Director ITFG & PA"),
    ("investment:6", "ITFG - Finance Team"),
    ("investment:7", "ITFG - Business Planning Team"),
    ("investment:8", "IG - Regeneration Investment Organisation (RIO)"),
    ("investment:9", "IG - Global Accounts - Director & Deputy Director & PA"),
    ("investment:10", "IG - Global Accounts - IT Software & Creative"),
    ("investment:11", "IG - Global Accounts - Electronics & Communications"),
    ("investment:12", "IG - Global Accounts - Financial & Business Services"),
    ("investment:13", "IG - Global Accounts - Energy & Infrastructure"),
    ("investment:14", "IG - Global Accounts - Adv Man - Auto, Rail MEPE"),
    ("investment:15", "IG - Global Accounts - Adv Man - Aero, Space, Chem"),
    ("investment:16", "IG - Global Accounts - Life Science, Agri- Tech"),
    ("investment:17", "IG - Global Operations - Global Entrepreneurs Programme"),
    ("investment:18", "IG - Global Operations - Graduate Entrepreneurs"),
    ("investment:19", "IG - Global Operations - Network Linkages & Professional Development"),
    ("investment:20", "IG - Global Operations - In Market Strategies & Development"),
    ("investment:21", "IG - Strategy/Policy/Local Engagement - Director & PA"),
    ("investment:22", "IG - Strategy/Policy/Local Engagement - Strategy"),
    ("investment:23", "IG - Strategy/Policy/Local Engagement - Global Intelligence"),
    ("investment:24", "IG - Strategy/Policy/Local Engagement - Local Engagement & Delivery"),
    ("investment:25", "IG - Strategy/Policy/Local Engagement - National & Local Policy"),
    ("investment:26", "IG - Specialists - Advanced Manufacturing"),
    ("investment:27", "IG - Specialists - Knowledge Intensive Industry"),
    ("investment:28", "IG - Specialists - Energy & Infrastructure"),
    ("investment:29", "IG - Specialists - Life Sciences"),
    ("investment:30", "IG - Finance & Business Planning"),
    ("investment:31", "IG - Global Intelligence Unit"),
    ("investment:32", "IG - SR - Strategic Accounts"),
    ("investment:33", "IG - SR - Institutional Investment"),
    ("investment:34", "IG - Global Operations - FDI Projects - Advanced Engineering"),
    ("investment:35", "IG - Global Operations - Director & PA"),
    ("investment:36", "IG - Global Operations - FDI Projects - Energy and Infrastructure"),
    ("investment:37", "IG - Global Operations - Briefing Tours and Visits"),
    ("investment:38", "IG - Global Operations and Network Performance"),
    ("investment:39", "IG - Global Operations - Deputy Director"),
    ("investment:40", "IG - Global Operations - Shared Services"),
    ("investment:41", "IG - UKAN Involvement"),
    ("investment:42", "IG - Strategy & Policy - Resources and Finance"),
    ("investment:43", "IG - Strategy & Policy - FDI Projects - Financial Services"),
    ("investment:44", "IG - Strategy & Policy - FDI Contract - Networks & Partnerships"),
    ("investment:45", "IG - Strategy & Policy - Investor Policy"),
    ("investment:46", "IG - Strategy & Policy - Briefing Tours and Visits"),
    ("investment:47", "IG - Strategy & Policy - Director & PA"),
    ("investment:48", "IG - Strategy & Policy - FDI Projects - Electronics and Comms"),
    ("investment:49", "IG - Strategy & Policy - Deputy Director"),
    ("investment:50", "IG - Strategy & Policy - Information Hub"),
    ("investment:51", "IG - Strategy & Policy - Local Policy & Engagement - DAs & Eng"),
    ("investment:52", "IG - CPI - FDI Projects - Life Sciences - Food & Drink"),
    ("investment:53", "IG - CPI - FDI Projects - New Technologies"),
    ("investment:54", "IG - Campaigns and Special Programmes"),
    ("investment:55", "IG - Tech City Investment Organisation"),

    ("dso:1", "DSO Head Office"),
    ("dso:2", "DSO Cyber Security Export Team"),
    ("dso:3", "DSO Business Development - Market Analysis"),
    ("dso:4", "DSO Director - Business Development - Events"),
    ("dso:5", "DSO - Business Development - Events"),
    ("dso:6", "DSO - Director - Business Development - Support to Business"),
    ("dso:7", "DSO - Head - Business Development - SME Team"),
    ("dso:8", "DSO - Business Development - Exportability"),
    ("dso:9", "DSO - Business Development - SME Team"),
    ("dso:10", "DSO - Business Development - Key Account Management"),
    ("dso:11", "DSO - Business Development - Mid Sized Businesses"),
    ("dso:12", "DSO - Director - RD1"),
    ("dso:13", "DSO - Deputy Director - RD 1"),
    ("dso:14", "DSO - RD 1A"),
    ("dso:15", "DSO - RD 1B"),
    ("dso:16", "DSO - RD 1C"),
    ("dso:17", "DSO - RD 1D"),
    ("dso:18", "DSO - RD 1E"),
    ("dso:19", "DSO - Director - RD2"),
    ("dso:20", "DSO - RD 2A"),
    ("dso:21", "DSO - Deputy Director - RD2"),
    ("dso:22", "DSO - RD 2B"),
    ("dso:23", "DSO - RD 2C"),
    ("dso:24", "DSO - RD 2D"),
    ("dso:25", "DSO - Senior Military Advisors"),
    ("dso:26", "DSO Policy and Resources"),
    ("dso:27", "DSO EM Exhibitions"),
    ("dso:28", "DSO Export Support Team (Bovington)"),
    ("dso:29", "DSO Export Support Team (Larkhill)"),
    ("dso:30", "DSO Director Business Development"),

    ("other:1", "UKTI Education"),
    ("other:2", "Healthcare UK"),
    ("other:3", "Offshore Wind Investment Organisation"),
    ("other:4", "Tech City Project"),
    ("other:5", "BG - Tech City"),
    ("other:6", "Financial Services Organisation (FSO)"),

    ("region:1", "East Midlands"),
    ("region:2", "East of England"),
    ("region:3", "London"),
    ("region:4", "North East"),
    ("region:5", "North West"),
    ("region:6", "Northern Ireland"),
    ("region:7", "Scotland"),
    ("region:8", "South East"),
    ("region:9", "South West"),
    ("region:10", "Wales"),
    ("region:11", "West Midlands"),
    ("region:12", "Yorkshire and The Humber"),

] + sorted([("post:{}".format(c[0]), str(c[1])) for c in countries.countries.items()], key=lambda x: x[1]))  # Attach standard countries list

TYPES = (
    (1, "Export Win"),
    (2, "Non-Export Win"),
    (3, "Mixed - Export and Non-Export Wins"),
)

TYPES_OF_SUPPORT = (
    (1, "Market entry advice and support – UKTI/FCO in UK"),
    (2, "Missions, tradeshows and events (UKTI/FCO)"),
    (3, "Advice, access and contacts – UKTI/FCO Overseas"),
    (4, "Political and economic briefing"),
    (5, "Lobbying to overcome a problem – UKTI/FCO"),
    (6, "Building positive reputation – UKTI/FCO"),
    (7, "Non-export : Outward Direct Investment – FCO"),
    (8, "Non-export : Reduced tax burdens – FCO"),
    (9, "Non-export : New Business in UK/3rd market – FCO"),
    (10, "Non-export : Other – FCO"),
)

WITHOUT_OUR_SUPPORT = (
    (1, "Would not have achieved any value"),
    (2, "1% – 20%"),
    (3, "21% - 40%"),
    (4, "41% - 60%"),
    (5, "61% - 80%"),
    (6, "81% - 99%"),
    (7, "All of it, the value would have been similar"),
)

# This is redundant, going 1:1 with HQ_TEAM_REGION_OR_POST above
UK_REGIONS = (
    (1, "East Midlands"),
    (2, "East of England"),
    (3, "London"),
    (4, "North East"),
    (5, "North West"),
    (6, "Northern Ireland"),
    (7, "Scotland"),
    (8, "South East"),
    (9, "South West"),
    (10, "Wales"),
    (11, "West Midlands"),
    (12, "Yorkshire and The Humber"),
)