# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0004_auto_20160607_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='business_type',
            field=models.PositiveIntegerField(choices=[(1, 'Outward investment'), (2, 'Contract'), (3, 'Order'), (4, 'Export sales'), (5, 'Distributor'), (6, 'Tender/competition win'), (7, 'Joint venture'), (8, 'Other (TEMPORARY)')], default=8, verbose_name='Other type of win'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='win',
            name='name_of_customer',
            field=models.CharField(default='', max_length=128, verbose_name='Name of the overseas customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='win',
            name='name_of_export',
            field=models.CharField(default='', max_length=128, verbose_name='Goods/services being exported'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='win',
            name='description',
            field=models.TextField(verbose_name='How was the company supported in achieving this win'),
        ),
    ]
