# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0005_auto_20160607_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='team_type',
            field=models.CharField(choices=[('team', 'Trade (TD or ST)'), ('investment', 'Investment (ITFG or IG)'), ('dso', 'DSO'), ('other', 'Other HQ Team'), ('region', 'UK Region'), ('post', 'Overseas Post')], max_length=128),
        ),
        migrations.AlterField(
            model_name='win',
            name='business_type',
            field=models.CharField(max_length=128, verbose_name='What kind of business deal best describes this win?'),
        ),
        migrations.AlterField(
            model_name='win',
            name='team_type',
            field=models.CharField(choices=[('team', 'Trade (TD or ST)'), ('investment', 'Investment (ITFG or IG)'), ('dso', 'DSO'), ('other', 'Other HQ Team'), ('region', 'UK Region'), ('post', 'Overseas Post')], max_length=128),
        ),
        migrations.AlterField(
            model_name='win',
            name='name_of_customer',
            field=models.CharField(max_length=128, verbose_name='What is the name of their overseas customer?'),
        ),
        migrations.AlterField(
            model_name='win',
            name='name_of_export',
            field=models.CharField(max_length=128, verbose_name=' What are the goods or services that are being exported?'),
        ),
    ]
