# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0007_auto_20160609_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='lead_officer_email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='win',
            name='other_official_email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
