# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0007_auto_20160609_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerresponse',
            name='access_to_contacts',
            field=models.PositiveIntegerField(choices=[(0, 'N/A'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Gained access to contacts not otherwise accessible?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='access_to_information',
            field=models.PositiveIntegerField(choices=[(0, 'N/A'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Gained access to information or improved understanding of the country?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='company_was_at_risk_of_not_exporting',
            field=models.BooleanField(verbose_name='Prior to securing this win, was your company at risk of not exporting?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='developed_relationships',
            field=models.PositiveIntegerField(choices=[(0, 'N/A'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Developed and/or nurtured critical relationships?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='expected_portion_without_help',
            field=models.PositiveIntegerField(choices=[(1, 'Would not have achieved any value'), (2, '1% – 20%'), (3, '21% - 40%'), (4, '41% - 60%'), (5, '61% - 80%'), (6, '81% - 99%'), (7, 'All of it, the value would have been similar')], verbose_name='What proportion of the total expected export value of this win would you have achieved without our support?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='gained_confidence',
            field=models.PositiveIntegerField(choices=[(0, 'N/A'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Gained the confidence to explore or expand in the country?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_enabled_expansion_into_existing_market',
            field=models.BooleanField(verbose_name='Has this win enabled you to expand into an existing market?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_enabled_expansion_into_new_market',
            field=models.BooleanField(verbose_name='Has this win enabled you to expand into a new market?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_increased_exports_as_percent_of_turnover',
            field=models.BooleanField(verbose_name='Has this win enabled you to increase exports as a % of your turnover?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='improved_profile',
            field=models.PositiveIntegerField(choices=[(0, 'N/A'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Improved your profile or credibility in the country?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='interventions_were_prerequisite',
            field=models.BooleanField(verbose_name='Were any of the interventions needed for this win a pre-requisite for the export value to be realised?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='involved_state_enterprise',
            field=models.BooleanField(verbose_name='Did the win involve a foreign government or state-owned enterprise? (e.g. as a customer, an intermediary or facilitator)'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='overcame_problem',
            field=models.PositiveIntegerField(choices=[(0, 'N/A'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Overcame a problem in the country (eg legal, regulatory, commercial)'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='support_improved_speed',
            field=models.BooleanField(verbose_name='Did our support or intervention(s) help you achieve this win more quickly than you otherwise would have done?'),
        ),
    ]
