# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0009_auto_20160609_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='description',
            field=models.TextField(verbose_name='How was the company supported in achieving this win?'),
        ),
        migrations.AlterField(
            model_name='win',
            name='is_prosperity_fund_related',
            field=models.BooleanField(verbose_name='Is this win Prosperity Fund related?'),
        ),
        migrations.AlterField(
            model_name='win',
            name='lead_officer_email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name="Lead officer's email address"),
        ),
        migrations.AlterField(
            model_name='win',
            name='lead_officer_name',
            field=models.CharField(help_text='This is the name that will be included in the email to the customer', max_length=128, verbose_name="Lead officer's name"),
        ),
        migrations.AlterField(
            model_name='win',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='win',
            name='other_official_email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name="Other officer's email address"),
        ),
    ]
