# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0010_auto_20160610_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresponse',
            name='case_study_willing',
            field=models.BooleanField(default=False, verbose_name='Would be willing to have your success featured as a UKTI / Exporting is GREAT case study?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerresponse',
            name='our_support',
            field=models.PositiveIntegerField(choices=[(0, 'N/A'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='How important was our support in securing the win?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='company_was_at_risk_of_not_exporting',
            field=models.BooleanField(verbose_name='Prior to securing this win, was your company at risk of stopping exporting?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='expected_portion_without_help',
            field=models.PositiveIntegerField(choices=[(1, 'Would not have achieved any export value without your support'), (2, 'Would have achieved 1% – 20% of the export value without your support'), (3, 'Would have achieved 21% - 40% of the export value without your support'), (4, 'Would have achieved 41% - 60% of the export value without your support'), (5, 'Would have achieved 61% - 80% of the export value without your support'), (6, 'Would have achieved 81% - 99% of the export value without your support'), (7, 'Would have achieved all of the export value without your support, the value would have been similar')], verbose_name='What proportion of the total expected export value above would you not have achieved without our support?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_enabled_expansion_into_existing_market',
            field=models.BooleanField(verbose_name='Has this win enabled you to maintain or expand in an existing market?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_explicit_export_plans',
            field=models.BooleanField(verbose_name='Do you have specific plans to export further in the next 12 months?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='interventions_were_prerequisite',
            field=models.BooleanField(verbose_name='Was any of the support we provided a prerequisite for the export value to be realised?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='last_export',
            field=models.PositiveIntegerField(choices=[(1, 'Not started exporting yet'), (2, 'Last 12 months'), (3, 'More than 1 year, less than 2'), (4, 'More than 2 years, less than 5'), (5, 'Over 5 years, less than 10'), (6, 'More than 10 years')], verbose_name='When did your company last export goods and/or services?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='support_improved_speed',
            field=models.BooleanField(verbose_name='Did our support help you achieve this win more quickly than you otherwise would have done?'),
        ),
    ]
