# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0013_auto_20160630_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerresponse',
            name='agree_with_win',
            field=models.NullBooleanField(verbose_name='Do you agree with the win details?'),
        ),
    ]
