# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0013_auto_20160630_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='win',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='wins.Win'),
            preserve_default=False,
        ),
    ]
