# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0014_advisor_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
