# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0016_auto_20160712_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerresponse',
            name='company_was_at_risk_of_not_exporting',
            field=models.BooleanField(default=False, verbose_name='Prior to securing this win, was your company at risk of stopping exporting?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_enabled_expansion_into_existing_market',
            field=models.BooleanField(default=False, verbose_name='Has this win enabled you to maintain or expand in an existing market?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_enabled_expansion_into_new_market',
            field=models.BooleanField(default=False, verbose_name='Has this win enabled you to expand into a new market?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_explicit_export_plans',
            field=models.BooleanField(default=False, verbose_name='Beyond this win, do you have specific plans to export in the next 12 months?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='has_increased_exports_as_percent_of_turnover',
            field=models.BooleanField(default=False, verbose_name='Has this win enabled you to increase exports as a % of your turnover?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='interventions_were_prerequisite',
            field=models.BooleanField(default=False, verbose_name='Was any of the support we provided a prerequisite for the export value to be realised?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='involved_state_enterprise',
            field=models.BooleanField(default=False, verbose_name='Did the win involve a foreign government or state-owned enterprise (e.g. as a customer, an intermediary or facilitator)?'),
        ),
        migrations.AlterField(
            model_name='customerresponse',
            name='support_improved_speed',
            field=models.BooleanField(default=False, verbose_name='Did our support help you achieve this win more quickly than you otherwise would have done?'),
        ),
    ]
