# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0016_win_updated'),
        ('wins', '0017_auto_20160801_1230'),
    ]

    operations = [
    ]
