# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 14:34
from __future__ import unicode_literals
from dateutil.relativedelta import relativedelta
import datetime

from django.db import migrations


def __str__(self):
    return "win {} - {} {}: {}K".format(
        self.win.id,
        self.year,
        'type: {}'.format(self.type),
        self.value / 1000,
    )


def do_thing(apps, schema_editor):
    Win = apps.get_model('wins', 'Win')
    Breakdown = apps.get_model('wins', 'Breakdown')
    now = datetime.datetime.utcnow()
    years = [(now + relativedelta(years=i)).year for i in range(0, 5)]
    for win in Win.objects.all():
        # print('\n\nexisting breakdowns for win {}:'.format(win.id), [__str__(b) for b in win.breakdowns.all()])
        year_to_export_breakdown = {}
        year_to_non_export_breakdown = {}
        for breakdown in win.breakdowns.all():
            if breakdown.type == 1:
                year_to_export_breakdown[breakdown.year] = breakdown
            elif breakdown.type == 2:
                year_to_non_export_breakdown[breakdown.year] = breakdown
        for year in years:
            if year not in year_to_export_breakdown:
                print('creating export breakdown for', year)
                b = Breakdown(
                    win=win,
                    type=1,
                    value=0,
                    year=year,
                )
                b.save()
            if year not in year_to_non_export_breakdown:
                print('creating non export breakdown for', year)
                b = Breakdown(
                    win=win,
                    type=2,
                    value=0,
                    year=year,
                )
                b.save()
        assert win.breakdowns.all().count() == 10, 'wrong number of breakdowns'


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0018_merge'),
    ]

    operations = [
        migrations.RunPython(do_thing),
    ]
