# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 13:57
from __future__ import unicode_literals

from django.db import migrations


def do_thing(apps, schema_editor):
    Win = apps.get_model('wins', 'Win')
    for win in Win.objects.all():
        if win.notifications.filter(type='c'):
            if not win.complete:
                print('marking complete win {}'.format(win))
                win.complete = True
                win.save()
            else:
                print('win {} is already complete'.format(win))
        else:
            print('win {} has not notification'.format(win))


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0019_auto_20160811_1434g'),
    ]

    operations = [
        migrations.RunPython(do_thing),
    ]
