# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0020_auto_20160815_1357b'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakdown',
            options={'ordering': ['year']},
        ),
    ]
